### ISSUE TITLE
recover after restart and wiser heathub reset 

### ISSUE THREAD

**Issue by scooper1** [asantaga/wiserHomeAssistantPlatform#125]
system working fine  - hassio reset for after hacs update 
get the following logs and no recovery even after wiser heathub power cycle - have to restart hassio again to reconnect 
using the latest beta

Logger: homeassistant.config_entries
Source: custom_components/wiser/__init__.py:201
First occurred: 20:49:30 (1 occurrences)
Last logged: 20:49:30

Error setting up entry WiserHeat037941 for wiser
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 436, in _error_catcher
    yield
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 766, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 719, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/usr/local/lib/python3.8/http/client.py", line 612, in _safe_read
    data = self.fp.read(amt)
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 571, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 792, in read_chunked
    self._original_response.close()
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/urllib3/response.py", line 454, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 234, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/wiser/__init__.py", line 96, in async_setup_entry
    await hass.async_add_executor_job(data.connect)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wiser/__init__.py", line 201, in connect
    self.wiserhub = wiserHub(self.host, self.secret)
  File "/usr/local/lib/python3.8/site-packages/wiserHeatingAPI/wiserHub.py", line 110, in __init__
    self.refreshData()  # Issue first refresh in init
  File "/usr/local/lib/python3.8/site-packages/wiserHeatingAPI/wiserHub.py", line 164, in refreshData
    resp = requests.get(
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 685, in send
    r.content
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 829, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 754, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

**Comment by msp1974** [comment]
It definitely not catching a chunked encoding error to try again. Will look at making it a little more robust.Sent from Samsung tablet.

**Comment by msp1974** [comment]
Next release will fix this.

**Comment by msp1974** [comment]
Just released v2.4beta3 with the fix for this.  If @scooper1 you could test and feedback, that would be appreciated.

**Comment by asantaga** [comment]
Closing this as fixed in 2.4beta3
