### ISSUE TITLE
 Error while setting up wiser platform for sensor

### ISSUE THREAD

**Issue by ryanxav** [asantaga/wiserHomeAssistantPlatform#130]
Home Assistant picks up rooms but no TRV's, no Hot Water. Installed through HACS, same result on master and beta channels. 

It worked initially, but next morning all TRV's and Hot Water were 'unavailable'. I've reinstalled and also rolled back Home Assistant VM to install fresh, but not got it working again with same error as below.

Any help greatly appreciated.

2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser Component Setup Completed
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser Heathub device init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser RoomStat-Kitchen device init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser RoomStat-Kitchen Battery Level device init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser iTRV-Hall device init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser iTRV-Hall Battery Level device init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser iTRV-Living Room device init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser iTRV-Living Room Battery Level device init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser iTRV-Kitchen device init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser iTRV-Kitchen Battery Level device init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser iTRV-Nursery device init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser iTRV-Nursery Battery Level device init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser iTRV-Landing device init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser iTRV-Landing Battery Level device init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser iTRV-Master Bedroom device init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser iTRV-Master Bedroom Battery Level device init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser iTRV-Play Room device init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser iTRV-Play Room Battery Level device init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser Valve Protection Switch Init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser Eco Mode Switch Init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser Away Mode Affects Hot Water Switch Init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser Comfort Mode Switch Init
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser Away Mode Switch Init
2020-11-28 08:30:38 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up wiser platform for sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/home/homeassistant/.homeassistant/custom_components/wiser/sensor.py", line 34, in async_setup_entry
    WiserDeviceSensor(data, device.get("id"), device.get("ProductType"))
  File "/home/homeassistant/.homeassistant/custom_components/wiser/sensor.py", line 253, in __init__
    self._device_name = self.get_device_name()
  File "/home/homeassistant/.homeassistant/custom_components/wiser/sensor.py", line 309, in get_device_name
    + self.data.wiserhub.getDeviceRoom(self._device_id)["roomName"]
  File "/srv/homeassistant/lib/python3.7/site-packages/wiserHeatingAPI/wiserHub.py", line 352, in getDeviceRoom
    return self.device2roomMap[deviceId]
KeyError: 10
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] Valve Protection: True
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] Eco Mode: None
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] Away Mode Affects Hot Water: True
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] Comfort Mode: True
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] Away Mode: None
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser Room Initialisation for Kitchen
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser Room Initialisation for Hall
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser Room Initialisation for Living Room
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser Room Initialisation for Nursery
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser Room Initialisation for Landing
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser Room Initialisation for Master Bedroom
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser Room Initialisation for Play Room
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] Wiser Room Initialisation for Second Bedroom
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] WiserRoom Update requested for Wiser Kitchen
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] State requested for room 1, state=Manual
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] WiserRoom Update requested for Wiser Hall
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] State requested for room 2, state=Manual
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] WiserRoom Update requested for Wiser Living Room
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] State requested for room 3, state=Manual
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] WiserRoom Update requested for Wiser Nursery
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] State requested for room 4, state=Manual
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] WiserRoom Update requested for Wiser Landing
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] State requested for room 5, state=Manual
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] WiserRoom Update requested for Wiser Master Bedroom
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] State requested for room 6, state=Manual
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] WiserRoom Update requested for Wiser Play Room
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] State requested for room 7, state=Manual
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] WiserRoom Update requested for Wiser Second Bedroom
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] State requested for room 8, state=Manual
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] **Wiser Hub data updated**
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] Wiser Valve Protection Switch Update requested
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] Valve Protection: True
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] Wiser Eco Mode Switch Update requested
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] Eco Mode: None
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] Wiser Away Mode Affects Hot Water Switch Update requested
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] Away Mode Affects Hot Water: True
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] Wiser Comfort Mode Switch Update requested
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] Comfort Mode: True
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] Wiser Away Mode Switch Update requested
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] Away Mode: None
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] WiserRoom Update requested for Wiser Kitchen
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] State requested for room 1, state=Manual
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] WiserRoom Update requested for Wiser Hall
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] State requested for room 2, state=Manual
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] WiserRoom Update requested for Wiser Living Room
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] State requested for room 3, state=Manual
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] WiserRoom Update requested for Wiser Nursery
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] State requested for room 4, state=Manual
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] WiserRoom Update requested for Wiser Landing
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] State requested for room 5, state=Manual
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] WiserRoom Update requested for Wiser Master Bedroom
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] State requested for room 6, state=Manual
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] WiserRoom Update requested for Wiser Play Room
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] State requested for room 7, state=Manual
2020-11-28 08:30:38 DEBUG (MainThread) [custom_components.wiser.const] WiserRoom Update requested for Wiser Second Bedroom
2020-11-28 08:30:38 INFO (MainThread) [custom_components.wiser.const] State requested for room 8, state=Manual

**Comment by msp1974** [comment]
@ryanxav, please see the instructions on this link.  
[Link](https://github.com/asantaga/wiserHomeAssistantPlatform/issues/126#issuecomment-721322399)

Can you provide this info.  Not really sure what the issue is here and this may help diagnose.  it seems to be looking for a TRV with ID 10 but looks like you only have 8 TRVs.

**Comment by ryanxav** [comment]
Thanks msp1974, done and attached.
[hub.log](https://github.com/asantaga/wiserHomeAssistantPlatform/files/5610346/hub.log)

**Comment by msp1974** [comment]
ok that helped a lot.  There's a couple of things about your hub that look odd.

1) It is showing as not paired.  Not really sure what this means but possibly not properly connected to wiser.  This is not the issue however, but not sure if it will cause any other issue.  It is on current firmware and connected to the cloud however.

2) Issue causing this error however, is because the hub has an entry for a TRV with ID 10 that does not belong to a room.  The code is failing when trying to get the room name of the TRV.  Again, not sure how you have this.

If you can see the TRV with no room in the app under devices, delete it.  If not, given issue 1 also, I would be tempted to reset your hub and set it up again.

**Comment by msp1974** [comment]
Should have also added, the TRV with ID 10 is not active and is not reporting any signal or temp.  Have you replaced one or do you have a faulty one?

**Comment by ryanxav** [comment]
1. Is that because I haven't created a cloud account? I'm intending to run local only for privacy reasons. Is it advised to connect to cloud?

2. I have hard reset the device and an 'unallocated' TRV has shown up. Deleted it and reloaded the integration and the TRV's etc. are back! Thank you! I had trouble with 1x TRV that I put away to try another day. I guess that's the issue.

**Comment by msp1974** [comment]
Not tried not having cloud account but if it works then it must be fine.  Glad its sorted.

**Comment by ryanxav** [comment]
Thanks again mate, really appreciate your help!
