### ISSUE TITLE
Errors om HA error log

### ISSUE THREAD

**Issue by davelegg83** [asantaga/wiserHomeAssistantPlatform#134]
Afternoon and Happy New year!
Got a few errors in my HA log, and just wondered if you knew what might be causing them. I had to reset my HA last night, so the issues have been since then, however they have showed up quite a few times before.

The first one is:

` Logger: custom_components.wiser.const
Source: custom_components/wiser/__init__.py:225
Integration: Wiser Heating Component for Home Assistant (documentation)
First occurred: 31 December 2020, 18:55:14 (4 occurrences)
Last logged: 15:16:18
Unable to update from Wiser hub due to timeout error`

The second one is: (This happened when I tried to do a 30 minute boost)

`

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/wiser/climate.py:509
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 15:15:53 (2 occurrences)
Last logged: 15:16:14

    [1897683432] HTTPConnectionPool(host='192.168.5.115', port=80): Max retries exceeded with url: //data/domain/Room/3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x69e30580>, 'Connection to 192.168.5.115 timed out. (connect timeout=5)'))
    [1897683432] HTTPConnectionPool(host='192.168.5.115', port=80): Max retries exceeded with url: //data/domain/Room/3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x69148fd0>, 'Connection to 192.168.5.115 timed out. (connect timeout=5)'))

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x69e30580>, 'Connection to 192.168.5.115 timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.5.115', port=80): Max retries exceeded with url: //data/domain/Room/3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x69e30580>, 'Connection to 192.168.5.115 timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/config/custom_components/wiser/climate.py", line 437, in async_set_preset_mode
    await self.set_room_mode(self.room_id, preset_mode, boost_temp, boost_time)
  File "/config/custom_components/wiser/climate.py", line 509, in set_room_mode
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/wiserHeatingAPI/wiserHub.py", line 826, in setRoomMode
    response = requests.patch(
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 149, in patch
    return request('patch', url, data=data, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.168.5.115', port=80): Max retries exceeded with url: //data/domain/Room/3 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x69e30580>, 'Connection to 192.168.5.115 timed out. (connect timeout=5)'))
`

Any advice appreciated

Dave

**Comment by msp1974** [comment]
This indicates that the hub is not responding within 5 seconds to a request.  Not sure what version of the wiser integration you are using but i think the latest beta version from Hacs puts the timeout up to 10 seconds.  You will need to enable beta versions in hacs to be able to get it.I presume the IP shown in the logs is the ip of your hub and it has not changed? Ie the hub integration is working ok otherwise? This timeout could also be an indication of a poor wifi signal on the hub.  If still happens with beta version check signal etc.MarkSent from my Galaxy

**Comment by davelegg83** [comment]
Hi Mark,
Many thanks for your reply. Currently running the latest version which I think is 2.4. Not sure how to try the beta version.
IP is exactly the same, checked at the time. In regards to the signal, it's currently in the room next to me.
Hopefully was just wiser having a funny 5 minutes!

Thanks for the great app, appreciate what you and others do to keep it updated and running.

**Comment by asantaga** [comment]
@msp1974 Is this 5seconds timeout a HA thing as part of its async flow? I just checked the wiserapi wiserhub code and our timeout is 15seconds..

**Comment by asantaga** [comment]
Ive been monitoring this and I dont see any issues in my instance.. Not sure if this is a problem but will close for now..
