### ISSUE TITLE
Issue with random failures in set_schedule service call

### ISSUE THREAD

**Issue by agitate** [asantaga/wiserHomeAssistantPlatform#139]
I get seemingly random failures for the set_schedule service call. I initially thought it was caused by calling the service too frequently, and I posted over on issue #48 about it, but I've since had a call to set_schedule fail, which is set as an automation in HA to run at 05:00, with no other calls within a few hours of it. Here is my schedule:

    Name: Wiser Kitchen
    Description: Normal Heating Schedule
    Type: Heating
    Weekdays:
      - Time: 06:50
        Temp: 21.0
      - Time: 08:20
        Temp: 14.0
      - Time: 18:30
        Temp: 21.0
      - Time: 22:30
        Temp: 14.0
    Weekends:
       - Time: 07:30
        Temp: 21.0
      - Time: 09:30
        Temp: 14.0
      - Time: 18:30
        Temp: 21.0
      - Time: 22:30
        Temp: 14.0

And here is my HA script to send it to the hub:

    alias: Set Normal Heating Schedule
    sequence:
      - service: wiser.set_schedule
        data:
          entity_id: climate.wiser_kitchen
          filename: schedules/normal.yaml
    mode: single
    icon: 'mdi:radiator'

I don't think it is an issue with the schedule file, or the script, because it works some times, but doesn't others. Here is the log of it failing to run early this morning:

    2021-01-30 05:00:00 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
    Traceback (most recent call last):
      File "/config/custom_components/wiser/__init__.py", line 505, in set_schedule
        await self._hass.async_add_executor_job(
      File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.8/site-packages/wiserHeatingAPI/wiserHub.py", line 564, in setSchedule
        raise WiserNotFound("No schedule found that matches id")
    wiserHeatingAPI.wiserHub.WiserNotFound: No schedule found that matches id

and here is a successful run from this morning (still run as an automation, I just moved the time, although it does sometimes happen when I run it manually too):

    2021-01-30 12:27:09 INFO (SyncWorker_4) [wiserHeatingAPI.wiserHub] Updating Wiser Hub Data
    2021-01-30 12:27:09 INFO (MainThread) [custom_components.wiser.const] **Wiser Hub data updated**
    2021-01-30 12:27:09 INFO (MainThread) [custom_components.wiser.const] State requested for room 1, state=Manual
    2021-01-30 12:27:09 INFO (MainThread) [custom_components.wiser.const] State requested for room 2, state=Auto
    2021-01-30 12:27:09 INFO (MainThread) [custom_components.wiser.const] State requested for room 3, state=Auto
    2021-01-30 12:27:09 INFO (MainThread) [custom_components.wiser.const] State requested for room 4, state=Auto
    2021-01-30 12:27:09 INFO (MainThread) [custom_components.wiser.const] State requested for room 5, state=Auto
    2021-01-30 12:27:09 INFO (MainThread) [custom_components.wiser.const] State requested for room 6, state=Auto
    2021-01-30 12:27:09 INFO (MainThread) [custom_components.wiser.const] State requested for room 7, state=Auto
    2021-01-30 12:27:09 INFO (MainThread) [custom_components.wiser.const] State requested for room 8, state=Auto

Over on the (possibly irrelevant issue #49) there was talk about this only happening within HA, not with the standalone API, so could it be a race condition in the calls to the update? I'm going to try and set up a test using the standalone API to see if I can confirm that (although I'll need to set all that up first). Any help or suggestions appreciated!

**Comment by asantaga** [comment]
Hey @agitate 

planning to make some tweaks in 1.26, just wondering is this still an issue,  I think this is a threading issue where the call you are doing happens whilst the integration is refreshing its state.

**Comment by asantaga** [comment]
@agitate Hey Adam, is this still an issue?

**Comment by agitate** [comment]
@asantaga Sorry about the late reply. Yes it is still happening. I've not been suitably motivated to set up the standalone API stuff and do any testing with that yet, unfortunately, but it does feel like a threading issue.

**Comment by asantaga** [comment]
:-( I hate threading issues, so tough to hunt down, and time is limited..

**Comment by asantaga** [comment]
Hey, i know this is an old issue, we've just released v3 beta, can u test this and see if the issues persist? Mark made a lotta changes to the way we talk to the heathub so these issues may be resolved

**Comment by asantaga** [comment]
Closing, lets see if the issues also occur with the v3 codebase
