### ISSUE TITLE
Invalid char in secret

### ISSUE THREAD

**Issue by jasonwins** [asantaga/wiserHomeAssistantPlatform#205]
I’ve upgraded to 3.x and get a error when supplying my secret:

JSONDecodeError: Invalid control character

Please can you help?

**Comment by jasonwins** [comment]
This error originated from a custom integration.

Logger: custom_components.wiser.config_flow
Source: custom_components/wiser/config_flow.py:51 
Integration: Drayton Wiser Integration for Home Assistant (documentation) 
First occurred: 22:25:15 (1 occurrences) 
Last logged: 22:25:15

Unknown error connecting to Wiser Hub
Traceback (most recent call last):
  File "/config/custom_components/wiser/config_flow.py", line 150, in async_step_zeroconf_confirm
    validated = await validate_input(self.hass, user_input)
  File "/config/custom_components/wiser/config_flow.py", line 51, in validate_input
    wiser = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/wiserHeatAPIv2/wiserhub.py", line 85, in __init__
    self.read_hub_data()
  File "/usr/local/lib/python3.9/site-packages/wiserHeatAPIv2/wiserhub.py", line 101, in read_hub_data
    _network_data = self._wiser_rest_controller._get_hub_data(WISERHUBNETWORK)
  File "/usr/local/lib/python3.9/site-packages/wiserHeatAPIv2/rest_controller.py", line 87, in _get_hub_data
    return response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Invalid control character '\x04' at: line 1 column 859 (char 858)

**Comment by asantaga** [comment]
the heathub can sometime return non printable chars in responses, in the past Ive seen it with SSIDs (see  https://github.com/asantaga/wiserheatingapi/issues/17 and https://github.com/asantaga/wiserheatingapi/pull/16/files)

The new 3.0 uses a new backend API and I think we need to apply the same PR 17 to this.

@msp1974

**Comment by asantaga** [comment]
Looked a the code and yes we need to tweak the new base API. Created https://github.com/msp1974/wiserHeatAPIv2/issues/1 with a potential fix.

Do any of your rooms/trvs/ssid have non ascii characters ?

Short term hack, if you dump the data from the hub (using postman etc) you'll quickly see what data is causing the issue and then rename the device

**Comment by jasonwins** [comment]
Downloaded the fix and it worked for me.
I have apostrophes in some of my room names. I have not updated the room names and the fix above resolved my issue.

**Comment by jasonwins** [comment]
Thanks for the quick response. Awesome project!

**Comment by msp1974** [comment]
R3.0.18 released which includes this fix in the api

**Comment by asantaga** [comment]
@jasonwins  Ive closed this as 3.0.18 fixes this, let us know if the problem still persistrs
