### ISSUE TITLE
'Cancel Boost' no longer working since latest update 

### ISSUE THREAD

**Issue by mousemat86** [asantaga/wiserHomeAssistantPlatform#218]
I have a 'Cancel Boost' button on a custom card which since the recent update has stopped working. I've pasted the log below. 

Here is the code for my button card:

```
         - type: custom:button-card
            icon: mdi:close-circle
            template: icon_name_extra
            tap_action:
              action: call-service
              service: climate.set_preset_mode
              service_data:
                preset_mode: 'Cancel Boost'
                entity_id: climate.wiser_main_thermostat
```

How can I fix it? Thanks!

```
 Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/config/custom_components/wiser/climate.py", line 262, in async_set_preset_mode
    elif WISER_PRESETS[preset_mode] == 0:
KeyError: 'Cancel Boost'`
```

**Comment by rlewis187** [comment]
The method has changed. Here is the code for my button that cancels ALL heating over rides:

```type: button
tap_action:
  action: call-service
  service: button.press
  service_data: {}
  target:
    entity_id: button.wiser_cancel_all_heating_overrides
show_state: false
icon_height: 60px
entity: button.wiser_cancel_all_heating_overrides
show_icon: true
name: Cancel Heat
```

**Comment by msp1974** [comment]
The preset has changed, so instead of Cancel Boost use Cancel Overrides.  Sent from my Galaxy

**Comment by asantaga** [comment]
@mousemat86 

Can you please confirm the above comments fix your issue and we can close this issue?

**Comment by mousemat86** [comment]
Hi thanks for the info. I'm yet to try updating my buttons but please do
close the issue if you need too.

**Comment by asantaga** [comment]
thanks closing for now, re open if needed
