### ISSUE TITLE
Unable to install package wiserHeatAPIv2==0.0.20: ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by tslytsly** [asantaga/wiserHomeAssistantPlatform#232]
Hi guys,
I updated to the latest version this morning and Wiser is not working anymore.
I get this error in the logs:
 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package wiserHeatAPIv2==0.0.20: ERROR: Command errored out with exit status 1:

I've updated HA to the latest version to, Home Assistant 2022.2.6.

I've tried removing and going back to 3.0.20, it's the same error.

**Comment by tslytsly** [comment]
More log output:

```command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bffrb9fr/ruamel-yaml-clib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bffrb9fr/ruamel-yaml-clib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lvm0ia8u
cwd: /tmp/pip-install-bffrb9fr/ruamel-yaml-clib/
Complete output (3 lines):
sys.argv ['/tmp/pip-install-bffrb9fr/ruamel-yaml-clib/setup.py', 'egg_info', '--egg-base', '/tmp/pip-pip-egg-info-lvm0ia8u']
test compiling /tmp/tmp_ruamel_47zvfkcr/test_ruamel_yaml.c -> test_ruamel_yaml compile error: /tmp/tmp_ruamel_47zvfkcr/test_ruamel_yaml.c

Exception: command 'gcc' failed: No such file or directory

----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

WARNING: You are using pip version 20.2; however, version 22.0.3 is available.

You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.[0m```

**Comment by asantaga** [comment]
i just updated my prod server to test it out and it works fine here..

now upgrading HA to .6 (from .5) to see if thats the issue

**Comment by msp1974** [comment]
How are you running HA?  We have updated ruamel.yaml in this latest release as the previous one is not compatible with Python 3.10 but it should be compatible with 3.6 and above.

The error seems you are missing gcc in your environment, which can be installed by installing build essentials.

Please provide the answer of what Linux OS and how you are running HA as we may find others with this issue.

**Comment by asantaga** [comment]
concur with mark, i just upgraded and no issues.

`sudo apt-get install build-essential` would work for Debian based systems (e.g. Ubuntu)

**Comment by tslytsly** [comment]
Hi,
This is a docker running inside Unraid.
This docker template:
lscr.io/linuxserver/homeassistant

**Comment by tslytsly** [comment]
in the meantime, can I downgrade to a version that does not require this?

**Comment by msp1974** [comment]
Should also add, we didn't used to include this requirement as HA had it as part of core (v2.6/2.7 was when we had to add it).  Not sure what your previous version of HA was but maybe you had it previously in core, which maybe why downgrading is also an issue.

**Comment by Fulch** [comment]
I also had the same error when updating from 3.0.20 to 3.0.21, deleting wiser integration and restarting Home Assistant before installing 3.0.20 with HACS worked for me. Also running HA 2022.2.6 as a container under Debian, not sure how to add the build essentials to the docker environment.
Downgrading from HACS did not work, only complete removal of wiser first followed by a reinstall of 3.0.20 was successful.

**Comment by asantaga** [comment]
@Fulch very weird.. I also run docker, with the official Homeassistant container and i dont have any issues

@tslytsly , is this the official home assistant docker container?

**Comment by Fulch** [comment]
@asantaga I run the same official HA container as you from the same repository but have the update problem, using Debian Buster as host OS.

**Comment by asantaga** [comment]
Weird.. 

Removing and reinstalling the integration should work and I dont think it will loose any config as the entity namers would be created the same..

Maybe we'd lose history.. 
Not sure about this, lets see if anyone else is hitting this

**Comment by tslytsly** [comment]
@asantaga , I'm using Linuxserver.io version, but it's just an exact copy of the official docker from HA. Build for running on Unraid.

**Comment by msp1974** [comment]
@tslytsly  and @Fulch can you please provide a HA info output to this issue - Configuration->Settings->Info.  I am running docker HA image on RPI4 buster, Dev direct git clone install on ubuntu 20.04 and I have run up a HA docker container on Debian Buster tonight - none of them show this error so think something is unusual with your setups and the info screen may help pinpoint this.  Thx

**Comment by Fulch** [comment]
@msp1974 Output as requested.
System Health

version: core-2022.2.7
installation_type: Home Assistant Container
dev: false
hassio: false
docker: true
user: root
virtualenv: false
python_version: 3.9.7
os_name: Linux
os_version: 4.19.0-17-amd64
arch: x86_64
timezone: Europe/London


GitHub API: ok
Github API Calls Remaining: 5000
Installed Version: 1.22.0
Stage: running
Available Repositories: 977
Downloaded Repositories: 13


logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok


dashboards: 1
resources: 8
views: 6
mode: storage

**Comment by msp1974** [comment]
ok I'm really stumped on this one.  I have created a new Debian Buster install (in vbox), no additional installs except running update to get latest versions, installed docker (with pre-requisites as per docker install instructions) and  docker-compose and used your docker-compose file to stand up a bare HA install (only changed config path).  Added HACs and Wiser custom integrations only - so it's about as pure as I can get and it worked without error.

Have you got the ability to run up another instance as I have done and see if it still errors?

**Comment by msp1974** [comment]
My info page for ref on this setup

## System Health

version | core-2022.2.7
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 4.19.0-18-amd64
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4913
Installed Version | 1.22.0
Stage | running
Available Repositories | 1049
Downloaded Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

**Comment by asantaga** [comment]
I also dont know. Have you tried creating a second docker container with homeassistant, obviously different port, and installing the integration there. If it works then its not the Host OS.
Other thing to try is [Fulch](https://github.com/Fulch) workaround which was to delete and reinstall the integration.. 

(obviously take a backup)

**Comment by tslytsly** [comment]
## System Health

version | core-2022.2.6
-- | --
installation_type | Unsupported Third Party Container
dev | false
hassio | false
docker | true
user | abc
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.10.28-Unraid
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4838
Installed Version | 1.22.0
Stage | running
Available Repositories | 987
Downloaded Repositories | 27

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 9
-- | --
resources | 17
views | 29
mode | yaml

</details>

**Comment by Fulch** [comment]
@msp1974 New instance created on same Buster machine, just HACS and Wiser 3.0.21 installed and no errors reported.

Only changed config directory and also deleted privileged: true in this docker compose file although you used my compose file with it present so I guess that has no bearing on the problem?

Did an exec into the new HA container and ran gcc --version result was "command not found" as I would expect, so for some reason in my original HA container HA does something different with the ruamel.yaml install which requires gcc to be present.

Found a couple of posts with similar problem although not with an HA container.
https://stackoverflow.com/questions/51046012/how-to-install-ruamel-yaml-w-o-native-extension
https://stackoverflow.com/questions/68626524/ruamel-yaml-requires-python-dev-in-ubuntu-container-build

Not sure where to go from here?

System Health

version: core-2022.2.7
installation_type: Home Assistant Container
dev: false
hassio: false
docker: true
user: root
virtualenv: false
python_version: 3.9.7
os_name: Linux
os_version: 4.19.0-18-amd64
arch: x86_64
timezone: Europe/London


GitHub API: ok
Github API Calls Remaining: 5000
Installed Version: 1.22.0
Stage: running
Available Repositories: 1049
Downloaded Repositories: 2


logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok


dashboards: 1
resources: 0
mode: auto-gen

**Comment by msp1974** [comment]
@Fulch - well that is some good news I think.  I wonder if you create a new docker container for HA (as you have done) and use your same config directory, does this work?  Obv back up the config dir first or create a copy to point this new docker to and see what happens.

**Comment by msp1974** [comment]
@tslytsly - like Angelo, I have no experience of using Unraid.  Are you able to do as @Fulch has done and run up another container with a fresh install of HA and try install wiser 3.0.21 in that to see if it works or not.  Maybe then try the same as I have suggested above.  It clearly as Fulch has seen, is something to do with the container and python doing something different to install ruamel.yaml than it should.

Other option is to run a shell within the container and install ruamel.yaml via pip and see if it installs this way.  If it already exists in the container, HA/wiser integration will not need to install it again.

**Comment by msp1974** [comment]
@Fulch - having read your second link, I wonder if something about your container (the one that errors) is unable to find a wheels download for your OS/python versions of ruamel.yaml.  According to this link ->
https://www.activestate.com/resources/quick-reads/python-install-wheel/
it seems that it will only try and compile from source if a whl file cannot be found.

The one difference between your original container and my test and your test ones is the linux kernel version.  Your original one is .17 and both our tests are .18.

Therefore I think ruamel.yaml does not have a whl file for 4.19.0-17-amd64/Python 3.9 but does for 4.19.0-18-amd64/Python 3.9.

@tslytsly I think this is the same issue, no whl for your version of linux/python.

I will research more if there is a way to get them to create whl for these versions.

**Comment by tslytsly** [comment]
thanks @msp1974

**Comment by msp1974** [comment]
> @msp1974 happy to try that. What is the command I need to run?

To shell into a HA docker container:
docker exec -it <container name> /bin/sh

**Comment by tslytsly** [comment]
> > @msp1974 happy to try that. What is the command I need to run?
> 
> To shell into a HA docker container: `docker exec -it <container name> /bin/sh`

Ah yea, I meant once I was in the docker exec environment :)

**Comment by Fulch** [comment]
@msp1974 Well spotted on the kernel version, before creating the new container I rebooted the server which must have then updated the kernel.
Now back to running the original HA container and have updated to wiser 3.0.21 without any problem.
I think you are spot on with the wheel not being available, many thanks for your insight and looking forward to many more happy hours using this integration.

**Comment by msp1974** [comment]
```pip install ruamel.yaml==0.17.20```Sent from my Galaxy
-------- Original message --------From: Tom Sealey ***@***.***> Date: 17/02/2022  14:31  (GMT+00:00) To: asantaga/wiserHomeAssistantPlatform ***@***.***> Cc: Mark Parker ***@***.***>, Mention ***@***.***> Subject: Re: [asantaga/wiserHomeAssistantPlatform] Unable to install package wiserHeatAPIv2==0.0.20: ERROR: Command errored out with exit status 1: (Issue #232) 


@msp1974 happy to try that. What is the command I need to run?

To shell into a HA docker container: docker exec -it <container name> /bin/sh

Ah yea, I meant once I was in the docker exec environment :)

**Comment by tslytsly** [comment]
@msp1974 ok did that. got this output:

```
WARNING: The directory '/config/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ruamel.yaml==0.17.20
  Downloading ruamel.yaml-0.17.20-py3-none-any.whl (109 kB)
     |████████████████████████████████| 109 kB 4.2 MB/s 
Collecting ruamel.yaml.clib>=0.2.6; platform_python_implementation == "CPython" and python_version < "3.11"
  Downloading ruamel.yaml.clib-0.2.6.tar.gz (180 kB)
     |████████████████████████████████| 180 kB 8.3 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7oja2qh8/ruamel-yaml-clib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7oja2qh8/ruamel-yaml-clib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-phb6hlah
         cwd: /tmp/pip-install-7oja2qh8/ruamel-yaml-clib/
    Complete output (3 lines):
    sys.argv ['/tmp/pip-install-7oja2qh8/ruamel-yaml-clib/setup.py', 'egg_info', '--egg-base', '/tmp/pip-pip-egg-info-phb6hlah']
    test compiling /tmp/tmp_ruamel_t3v9ooiw/test_ruamel_yaml.c -> test_ruamel_yaml compile error: /tmp/tmp_ruamel_t3v9ooiw/test_ruamel_yaml.c
    Exception: command 'gcc' failed: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2; however, version 22.0.3 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
```

Is there a way around this? My server is on the latest version. so I cannot update the OS.

**Comment by msp1974** [comment]
OK, it definitely seems that there is no wheels file for ruamel.yaml.clib for your version of linux in the Unraid release.  As this is an unsupported way to run HA, think you have 2 options.

1) See this link and shell into your docker container and install the suggested packages (worth reading the whole thing as this is exactly the issue you have but packages are on last comment).
https://stackoverflow.com/questions/69287269/installing-ruamel-yaml-clib-with-docker
2) Speak to whoever maintains this image and ask if those packages can be included in the image
3) Log an issue with ruamel.yaml to see if they can create a wheels for the clib requirement for your environment - don't know all the details so cannto do for you.  You will need to know what flavour and version of linux is running in the container.

**Comment by tslytsly** [comment]
yea, I logged in and installed those packages.
Now 3.0.21 installs fine.
Thanks

**Comment by tslytsly** [comment]
For anyone who comes across this issue in future, you can customize the linuxserver.io containers very easily, see this link:
https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers

Basically, you need to add a script to the `/config/custom-cont-init.d` folder.
This get's executed at startup of the container.
I added: `add-gcc.sh`
which contains
```
#!/bin/bash

echo "**** installing gcc musl-dev python3-dev ****"
apk add --no-cache gcc musl-dev python3-dev
```

All fixed now.
Thanks @msp1974  and @asantaga  and @Fulch  for helping diagnose the issue

**Comment by msp1974** [comment]
Fantastic.  Glad we have you both working now.

**Comment by LGO44** [comment]
Thanks @msp1974 

here is a doc how I solve this issue with your hel
[Install wiserHeatAPIv2.pdf](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8100752/Install.wiserHeatAPIv2.pdf)
p

**Comment by LGO44** [comment]
after my installation of the new API, I get this kind of message in the logs

_2022-02-19 00:58:48 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139699095203408] '_WiserLight' object has no attribute 'turn_off'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 190, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 513, in async_handle_light_off_service
    await light.async_turn_off(**filter_turn_off_params(light, params))
  File "/config/custom_components/wiser/light.py", line 372, in async_turn_off
    self._light.turn_off
AttributeError: '_WiserLight' object has no attribute 'turn_off'_

I think that the API is not well installed or is not in the right place.
As you can see I have installed it from the config folder this can be my mistake.
Where does it need to bee installed?

Thanks in advance

**Comment by JoshuaRedmond** [comment]
Hi everyone. 

I've also seen the same issue as reported by @tslytsly - namely `Unable to install package wiserHeatAPIv2==0.0.20: ERROR` in the logs after upgrading to HA 2022.2.5 (and later 2022.2.9) and WiserHA 3.0.21. Running the pip ruamel command gave me an identical result too (a compile error in test_ruamel_yaml.c where gcc is throwing "no such file or directory"). 

However, where I differ is that I'm using the official HomeAssistant Docker image. homeassistant/home-assistant:stable. Did the fix of recreating the container work for anyone else? Or did the underlying image change cause this? Happy to provide more information to assist if it would help.

**Comment by msp1974** [comment]
@JoshuaRedmond - can you please provide a HA info output to see what linux kernel you are running.  Can you also provide info on what host OS/Platform you are running HA docker image.  Thx

**Comment by JoshuaRedmond** [comment]
Thanks @msp1974. I'm running docker 19.03.12, in a VM of Alpine 9.3.0, on TrueNAS Core 12. HA Info below:
## System Health

version | core-2022.2.9
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.4.72-0-virt
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4766
Installed Version | 1.23.0
Stage | running
Available Repositories | 993
Downloaded Repositories | 32

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 18 March 2022, 00:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-west-2-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 6
-- | --
resources | 21
views | 21
mode | storage

</details>

**Comment by msp1974** [comment]
Hmm, that's not something I can test anything on.  I would guess it is the same issue that ruamel.yaml does not have a precompiled wheel for your env and therefore when trying to compile fails.

For now, you can shell into the docker container and run
```
apk add --no-cache gcc musl-dev python3-dev
```
and then restart it and it should allow you to upgrade to 3.0.21.

I'm going to reopen this issue to see if there is a way to prevent these issues going forward.

**Comment by JoshuaRedmond** [comment]
Thanks @msp1974 , that's fixed my instance for now. I think you're right about the precompiled wheel issue - is there anything I can do to help you investigate it further?

**Comment by tombadog99** [comment]
Just a note to say that I also had this issue and fixed it in my instance with the above steps but would be good if there was a way to prevent this issue in the future.

**Comment by asantaga** [comment]
Alas this is a docker image/host issue. Ill speak to a python  docker guru at work and see if rhere is anything we can do

**Comment by msp1974** [comment]
> Just a note to say that I also had this issue and fixed it in my instance with the above steps but would be good if there was a way to prevent this issue in the future.

@tombadog99 can you also please provide details of your environment you are running HA in?

**Comment by tombadog99** [comment]
> > Just a note to say that I also had this issue and fixed it in my instance with the above steps but would be good if there was a way to prevent this issue in the future.
> 
> @tombadog99 can you also please provide details of your environment you are running HA in?

I am using the Linuxserver.io homeassistant docker container. Let me know if you need any more info.

**Comment by msp1974** [comment]
Just an update for all on this issue.  I have been looking into how we can resolve this and the issue is basically this:

ruamel.yaml has a dependancy of ruamel.yaml.clib
There is no wheel for current versions of alpine for the latest version 0.2.6 of ruamel.yaml.clib on python 3.9 and is to do with the fact that alpine linux has different libraries used from all other versions of linux.

We (I) updated the version of ruamel.yaml to 0.17.20 and the previous version 0.15.100 would not compile on python 3.10 which HA will be going to sometime soon.

However, it appears that ruamel.yaml 0.16.10 does not try to install the ruamel.yaml.clib dependancy (which is also not actually needed by this integration), so we will be updating the api to use this version and issue a 0.3.22 release with this in it.

Would be great to get feedback from you all if this has solved the problem once released.  It will be this week sometime.

**Comment by tslytsly** [comment]
@msp1974 thanks for this.
That's great. 
Let me know when the new version is released, and I'll do some testing. :)

**Comment by tombadog99** [comment]
Thanks, also happy to test when released.

**Comment by msp1974** [comment]
All,  I have just published a pre-release v3.0.22beta version.  You will need to have beta versions allowed in HACs to be able to download.  If you have installed the gcc musl-dev python3-dev packages, you will need to uninstall them to test properly.

If those who were having issues could try this and feed back if it now resolves the issue.  Thanks

**Comment by tslytsly** [comment]
Hi, 
I removed gcc, musl-dev, python3-dev and then updated the integration to 3.0.22beta. working with no issues. 
Thanks @msp1974

**Comment by tombadog99** [comment]
Can also confirm that 3.022beta is working without any major problems. Many thanks!
