### ISSUE TITLE
new schedule services

### ISSUE THREAD

**Issue by LGO44** [asantaga/wiserHomeAssistantPlatform#248]
With the branch lgo44, everything works fine ( very good job Mark ) except the services get_schedule, set schedule, copy_schedule don't run properly
the deprecated services are OK, but the new one not.
When I try to test I have nothing in the select entity 

![image](https://user-images.githubusercontent.com/95585425/159884851-c8bdf56f-fec6-4c7f-ba43-c797031868e9.png)

when I fill it manually in the UI or un yaml mode I get an error.

extract of the logs with deprecated services and new ones:

**2022-03-24 10:02:13 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2022-03-24 10:02:13 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2022-03-24 10:02:13 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['entity']
2022-03-24 10:02:13 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139874771863776] Error handling message: extra keys not allowed @ data['entity']. Got None
required key not provided @ data['entity_id']. Got None
2022-03-24 10:04:19 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2022-03-24 10:04:19 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2022-03-24 10:04:19 WARNING (MainThread) [custom_components.wiser.climate] The Save Heating Schedule to File service is deprecated and will be removed in a future release.  Please use the Save Schedule to File service instead
2022-03-24 10:04:19 INFO (MainThread) [custom_components.wiser.climate] Saving Salle_Salon schedule to file prog_chauffage_salon.yaml
2022-03-24 10:05:13 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2022-03-24 10:05:13 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2022-03-24 10:05:13 WARNING (MainThread) [custom_components.wiser.climate] The Save Heating Schedule to File service is deprecated and will be removed in a future release.  Please use the Save Schedule to File service instead
2022-03-24 10:05:13 INFO (MainThread) [custom_components.wiser.climate] Saving Salle_Salon schedule to file prog_chauffage_salon2.yaml
2022-03-24 10:07:52 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2022-03-24 10:07:52 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2022-03-24 10:07:52 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['entity']
2022-03-24 10:07:52 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139874771863776] Error handling message: extra keys not allowed @ data['entity']. Got None
required key not provided @ data['entity_id']. Got None
2022-03-24 10:15:19 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2022-03-24 10:15:19 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2022-03-24 10:15:19 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['entity']
2022-03-24 10:15:19 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139874771863776] Error handling message: extra keys not allowed @ data['entity']. Got None
required key not provided @ data['entity_id']. Got None**

Thanks 
Christian

**Comment by msp1974** [comment]
OK ket me look at that and I'll put a fix into the lgo44 branch and let you know when there.Sent from my Galaxy

**Comment by msp1974** [comment]
@LGO44 do you want to update from the lgo44 branch and test these services now.  I need to look at the deprecated services and make sure they are still fully working (think they are as you say), which I will do over the weekend.  This may also be an issue in v3.0.23 release, so may need a v3.0.23patch1 release to fix as all this work will be v3.0.24

**Comment by msp1974** [comment]
@LGO44 - having looked at the services, I have also made changes to the set mode services to consolidate down to a single set_device_mode service and deprecated set_smartplug_mode, set_hotwater_mode and removed your new set_shutter_mode, set_light_mode services.  This is to both keep the list of services simpler and also remove lots of unnecessary code.

Again, please can you test these also.

**Comment by LGO44** [comment]
@msp1974 
Thanks for your job
I have made some tests  on the services with your last modifications , détails in the joined file
The results are those that are expected
I copied a dimmablelight schedule to the new **onofflight** schedule

Question
In the UI mode the list box "entity" is not filled, so you have to fill it with the keyboard. Is it normal?
When I use the copy schedule the list box "to entity" propose the list of entities.
![image](https://user-images.githubusercontent.com/95585425/160019182-4d250bf0-e479-4a47-8409-2a48987bf271.png)
[test schedule services.pdf](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8346081/test.schedule.services.pdf)

**Comment by LGO44** [comment]
_@LGO44 - having looked at the services, I have also made changes to the set mode services to consolidate down to a single set_device_mode service and deprecated set_smartplug_mode, set_hotwater_mode and removed your new set_shutter_mode, set_light_mode services. This is to both keep the list of services simpler and also remove lots of unnecessary code.

Again, please can you test these also._

Please also note - you can call the set_device_mode on many entities at the same time and set them to the same mode.

Sorry I haven't seen yuor post I shall test this tomorrow

**Comment by LGO44** [comment]
**@msp1974** 

1. I have tested the new set mode service, that's OK.

2. When I want to select the entity in the UI , if I select area and device I get an error:

_2022-03-25 10:30:14 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['area_id']
2022-03-25 10:30:14 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139904705743216] Error handling message: extra keys not allowed @ data['area_id']. Got None
extra keys not allowed @ data['device_id']. Got None_

If I select only the entity it works.

3. With this new version I get another issue when I want to  set the position of shutters:

2022-03-25 10:11:04 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139904919074368] 'int' object is not callable
Traceback (most recent call last):
  File "/home/christian/development/core/homeassistant/components/websocket_api/commands.py", line 191, in handle_call_service
    await hass.services.async_call(
  File "/home/christian/development/core/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/home/christian/development/core/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/home/christian/development/core/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/home/christian/development/core/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/home/christian/development/core/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/home/christian/development/core/custom_components/wiser/cover.py", line 194, in async_set_cover_position
    await self.hass.async_add_executor_job(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: 'int' object is not callable

I won't be at home this week-end
Thanks

**Comment by msp1974** [comment]
Ok, both of these issues should be fixed and pushed into the lgo44 branch

1) Set cover position now calls the setattr function correctly
2) The set_device_mode service now only allows selection of an entity and not areas or devices

I see from your test result documents, we could improve how it handles setting/copying a schedule if the device does not have one already.  I will look into improving that.

**Comment by msp1974** [comment]
Are these all working now.  Can we close this issue?

**Comment by LGO44** [comment]
@msp1974 
please excuse me for not giving the results.
Positives of course, so you can close the issue
Thanks
