### ISSUE TITLE
Identify switches for lights and shutters

### ISSUE THREAD

**Issue by LGO44** [asantaga/wiserHomeAssistantPlatform#250]
**@msp1974** 
I tested the version of the **platform 3.0.24 and the wiserHatAPIv2 0.26**.
 Very good job Mark , everything fine for the ligths (dimmable and onoff), the services OK 👍 

For the identification , only the heat (roomstat, heatingactuators) are Ok

- when I want to identify cuisine_lustre_light then the wiser_roomstat_salle_salon_identify is set  and the roomstat is in identify mode but nor the light.

![image](https://user-images.githubusercontent.com/95585425/160566891-c0eb4da1-ee71-4064-a0ac-4a41c5fe760c.png)

- for exemple : when I want to identify a dimmable light I get an issue : 

_2022-03-29 09:53:20 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140076581083552] Rest endpoint not found on Wiser Hub 1xx.xxx.xxx.xxx
Traceback (most recent call last):
  File "/home/christian/development/core/homeassistant/components/websocket_api/commands.py", line 191, in handle_call_service
    await hass.services.async_call(
  File "/home/christian/development/core/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/home/christian/development/core/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/home/christian/development/core/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/home/christian/development/core/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/home/christian/development/core/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/home/christian/development/core/custom_components/wiser/switch.py", line 334, in async_turn_on
    await self.hass.async_add_executor_job(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/christian/development/wiserHeatAPIv2/wiserHeatAPIv2/light.py", line 106, in identify
    if self._send_command({"Identify": enable}, True):
  File "/home/christian/development/wiserHeatAPIv2/wiserHeatAPIv2/light.py", line 43, in _send_command
    result = self._wiser_rest_controller._send_command(WISERDEVICE.format(self.light_id), cmd)
  File "/home/christian/development/wiserHeatAPIv2/wiserHeatAPIv2/rest_controller.py", line 171, in _send_command
    if self._patch_hub_data(url, command_data):
  File "/home/christian/development/wiserHeatAPIv2/wiserHeatAPIv2/rest_controller.py", line 117, in _patch_hub_data
    self._process_nok_response(response)
  File "/home/christian/development/wiserHeatAPIv2/wiserHeatAPIv2/rest_controller.py", line 147, in _process_nok_response
    raise WiserHubRESTError(
wiserHeatAPIv2.exceptions.WiserHubRESTError: Rest endpoint not found on Wiser Hub 1xx.xxx.xxx.xxx

- for shutters :  

022-03-29 10:13:25 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140076579051216] Rest endpoint not found on Wiser Hub 1xx.xxx.xxx.xxx
Traceback (most recent call last):
  File "/home/christian/development/core/homeassistant/components/websocket_api/commands.py", line 191, in handle_call_service
    await hass.services.async_call(
  File "/home/christian/development/core/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/home/christian/development/core/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/home/christian/development/core/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/home/christian/development/core/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/home/christian/development/core/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/home/christian/development/core/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/home/christian/development/core/custom_components/wiser/switch.py", line 342, in async_turn_off
    await self.hass.async_add_executor_job(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/christian/development/wiserHeatAPIv2/wiserHeatAPIv2/shutter.py", line 148, in identify
    if self._send_command({"Identify": enable}, True):
  File "/home/christian/development/wiserHeatAPIv2/wiserHeatAPIv2/shutter.py", line 74, in _send_command
    result = self._wiser_rest_controller._send_command(WISERDEVICE.format(self.shutter_id), cmd)
  File "/home/christian/development/wiserHeatAPIv2/wiserHeatAPIv2/rest_controller.py", line 171, in _send_command
    if self._patch_hub_data(url, command_data):
  File "/home/christian/development/wiserHeatAPIv2/wiserHeatAPIv2/rest_controller.py", line 117, in _patch_hub_data
    self._process_nok_response(response)
  File "/home/christian/development/wiserHeatAPIv2/wiserHeatAPIv2/rest_controller.py", line 147, in _process_nok_response
    raise WiserHubRESTError(
wiserHeatAPIv2.exceptions.WiserHubRESTError: Rest endpoint not found on Wiser Hub 1xx.xxx.xxx.xxx

**Comment by msp1974** [comment]
Are you able to do in app and provide the http command via httpcanary?Sent from my Galaxy

**Comment by msp1974** [comment]
Actually, think I have found the issue.  For some reason lights and shutters have 2 IDs.  A device ID and a light ID or shutter ID.  The command called for identify was using light id/shutter id instead of device id.

This is an issue with the wiserHeatAPIv2 - the changes are pushed in the master branch on the repo.

Can you test and let me know.  Thx

**Comment by LGO44** [comment]
here are the canary informations. This file gathered all the requests for lights and shutters and the deviceidentification and devicelockenable for Roomstat.
I agree , for the identification and lock the request is not for light, shutter, smartplug ... but for  **device** and **deviceid**.
I'll make the tests this afternoon
[Wiser light commands.pdf](https://github.com/asantaga/wiserHomeAssistantPlatform/files/8371417/Wiser.light.commands.pdf)

**Comment by LGO44** [comment]
@msp1974 
Now we can identify correctly our lights and shutters without any mismatched with the other components.
Only the smartplugs have no identification.
very good job Mark
Thanks.

**Comment by msp1974** [comment]
Sorry should say - added identify to smartplug in api which will work in HA once restarted.

**Comment by LGO44** [comment]
the identification of the smartplugs run very well thank you.

For the device lock, I looked deeper in the Wiser Home smartphone application, this feature is not available even if the property exist.
Now I think that it's not necessary to add them in the API.
Another time thank you very much Mark for all your help.
