### ISSUE TITLE
Schedule Card resource install fails if using YAML storage for Lovelace

### ISSUE THREAD

**Issue by msp1974** [asantaga/wiserHomeAssistantPlatform#270]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/wiser/__init__.py", line 400, in async_setup_entry
    resource_id = await hass.data['lovelace']["resources"].async_create_item({"res_type":"module", "url":url})
AttributeError: 'ResourceYAMLCollection' object has no attribute 'async_create_item'

**Comment by msp1974** [comment]
This is new code in v3.1.0 to 'install' the schedule card.  I'm going to get it to check that it is running in storage mode.  Not familiar with YAML mode, I presume you have to manually add resources if you want to use?

**Comment by msp1974** [comment]
This is now fixed in v3.1.1.
