### ISSUE TITLE
setup not working for me - seems like JSON parse issue

### ISSUE THREAD

**Issue by hueytech** [asantaga/wiserHomeAssistantPlatform#3]
Using latest release I get;
2018-11-30 18:43:51 ERROR (MainThread) [homeassistant.setup] Error during setup of component wiser
Traceback (most recent call last):
  File "f:\python\homeassistant\lib\site-packages\homeassistant\setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "C:\Users\spw\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\spw\AppData\Roaming\.homeassistant\custom_components\wiser.py", line 44, in setup
    hass.data[DATA_KEY] = WiserHubHandle(hubHost, password, scan_interval)
  File "C:\Users\spw\AppData\Roaming\.homeassistant\custom_components\wiser.py", line 63, in __init__
    self.wiserHub=wiserHub.wiserHub(self.ip,self.secret)
  File "C:\Users\spw\AppData\Roaming\.homeassistant\custom_components\wiserAPI\wiserHub.py", line 29, in __init__
    self.refreshData()          # Issue first refresh in init
  File "C:\Users\spw\AppData\Roaming\.homeassistant\custom_components\wiserAPI\wiserHub.py", line 42, in refreshData
    for **valveId in smartValves**:
TypeError: 'NoneType' object is not iterable

attached is the JSON dump obtained by doing a wireshark while HA was doing it's discovery.
[wiser debug network trace2.txt](https://github.com/asantaga/wiserHomeAssistantPlatform/files/2634693/wiser.debug.network.trace2.txt)

**Comment by asantaga** [comment]
I think the heatHub has corrupted data. If you look at the data for rooms we see rooms with
a) Empty Arrays for radiators 
    e.g. Living room and Dinning room (misspelt!) shows  **SmartValveIds": [],**, which is a bit weird..that you have a room with no valves
b) conservatory doesnt even have a SmartValveIds element! nada (which is the cause of the error)

Have coded some guards around the queries, try replacing wiserAPI/wiserHub.py
 with this one https://raw.githubusercontent.com/asantaga/wiserHomeAssistantPlatform/master/wiserAPI/wiserHub.py

**Comment by hueytech** [comment]
Super - all good here now. TY!

**Comment by asantaga** [comment]
code fix committed
