### ISSUE TITLE
Problem setting away/home modes

### ISSUE THREAD

**Issue by partymike** [asantaga/wiserHomeAssistantPlatform#30]
Hiya, thanks for this component your work is very much appreciated.

Running Hassio 0.99.3 & wiser 1.5 via HACS, default setup with all kit reporting status correctly.

Having an issue setting away mode, see the following error:

"Failed to call service switch/turn_on. Error setting Home/Away, error {"Type":"Away","SetPoint":50}

Not too sure why it won't change the home/away status via simple switch click?

**Comment by asantaga** [comment]
mmm ive been so busy at work I havent upgraded my HAAS environment.. or gotten my a*** off to publish it as a component in HA..

I'll look at this when I can.. maybe this weekend ok

Any other error messages?

**Comment by partymike** [comment]
I see this when the automation runs that should switch the away to off:

2019-10-04 15:57:35 ERROR (MainThread) [homeassistant.components.automation] Error while executing automation automation.arrive_home_heating_on. Unknown error for call_service at pos 1: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 434, in action
    await script_obj.async_run(variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 162, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 246, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 329, in _async_call_service
    context=context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 98, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1259, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 349, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 371, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wiser/switch.py", line 69, in turn_off
    self.handler.set_away_mode(False, self.awayTemperature)
  File "/config/custom_components/wiser/__init__.py", line 163, in set_away_mode
    self.wiserHubInstance.setHomeAwayMode(mode, away_temperature)
  File "/usr/local/lib/python3.7/site-packages/wiserHeatingAPI/wiserHub.py", line 169, in setHomeAwayMode
    raise Exception("Error setting Home/Away , error {} ".format(self.response.text))
Exception: Error setting Home/Away , error {"Type":"None","SetPoint":0}

**Comment by asantaga** [comment]
Hey I was checking this out and my dev environment is all up the swannie.. I was able to test out the core API and its all working fine. Looking at the stack trace the error appears to be that set away home method is being called without the required parameters.. Just for completeness how are you calling the swtich?

**Comment by asantaga** [comment]
reinstalling dev environment, looks like HA development has changed (for the better)  
a lot since I last did some dev work..

**Comment by partymike** [comment]
since updating to 0.100.2 its now working so not sure what they have changed but the automation is now correctly setting the home/away state! :-)

**Comment by asantaga** [comment]
awesome... i was looking at this and was baffled,,  :-)
