### ISSUE TITLE
 New install similar to Config Error #291 

### ISSUE THREAD

**Issue by spangingpan** [asantaga/wiserHomeAssistantPlatform#322]
I am getting the same error as seen in the previous bug post:
2022-11-01 16:23:59.619 ERROR (MainThread) [custom_components.wiser.config_flow] Unknown error connecting to Wiser Hub
Traceback (most recent call last):
File "/config/custom_components/wiser/config_flow.py", line 157, in async_step_zeroconf_confirm
validated = await validate_input(self.hass, user_input)
File "/config/custom_components/wiser/config_flow.py", line 59, in validate_input
await wiserhub.read_hub_data()
File "/usr/local/lib/python3.10/site-packages/aioWiserHeatAPI/wiserhub.py", line 122, in read_hub_data
self._network_data = await self._wiser_rest_controller._get_hub_data(
File "/usr/local/lib/python3.10/site-packages/aioWiserHeatAPI/rest_controller.py", line 145, in _get_hub_data
return await self._do_hub_action(
File "/usr/local/lib/python3.10/site-packages/aioWiserHeatAPI/rest_controller.py", line 101, in _do_hub_action
if len(await response.text()) > 0:
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1085, in text
return self._body.decode( # type: ignore[no-any-return,union-attr]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 927: invalid start byte

I have been using Wiser for years and have schedules set up in the app for various rooms. I have not used the HA wiser plugin before.
Can you please help me get it to work.

versions are all the latest:
 Home Assistant 2022.10.5 Supervisor 2022.10.0 Operating System 9.3 Frontend 20221010.0 - latest

**Comment by msp1974** [comment]
Sorry, we've had this issue before and with the 3.2 api update, I forgot to include the fix back in!  I will be releasing v3.2.2 later this week which should solve it for you.  In the meantime, you can install v3.1.7 which will work.

**Comment by spangingpan** [comment]
That made a big difference, thanks! I was getting stuck and thought it was user error.

**Comment by msp1974** [comment]
Would you try v3.2.2 and see if this is now resolved.  Thanks

**Comment by spangingpan** [comment]
I updated using the HAC process, it worked great and all of the data appears to be populating the dashboards. Just upgraded homeassistant as that appears to have a new update: 2022.11.2.
Everything is still working, thanks for the quick fix.
