### ISSUE TITLE
Shutter set away mode

### ISSUE THREAD

**Issue by LGO44** [asantaga/wiserHomeAssistantPlatform#329]
When I try to set the away mode _switch.wiser_shutter_room_name_away_mode_closes_ I get an error .
It OK for lights, smartplugs.

https://user-images.githubusercontent.com/95585425/203650427-5d275185-3a3a-44cd-b4ff-7e0c50bf4d7f.mp4

logs:

2022-11-23 22:30:04.908 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140427191013280] '_WiserShutter' object has no attribute 'set_'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/wiser/switch.py", line 635, in async_turn_off
    fn = getattr(self._shutter, "set_" + self._key)
AttributeError: '_WiserShutter' object has no attribute 'set_'

2022-11-23 22:30:14.359 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140427191013280] 'f_WiFor lightsserShutter' object has no attribute 'set_'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/wiser/switch.py", line 628, in async_turn_on
    fn = getattr(self._shutter, "set_" + self._key)
AttributeError: '_WiserShutter' object has no attribute 'set_'

**Comment by LGO44** [comment]
@msp1974 best wishes for this new year
Sorry I forgot to give the feed back, of course this issue is fixed.

**Comment by LGO44** [comment]
@msp1974  I confirm the error is fixed in version 3.2.3beta
Thanks

**Comment by msp1974** [comment]
Closing as resolved in current beta release
