### ISSUE TITLE
Error configuring 

### ISSUE THREAD

**Issue by Rhysgh** [asantaga/wiserHomeAssistantPlatform#344]
Sorry for a silly ticket, but i can't get this configured. 

![image](https://user-images.githubusercontent.com/57257743/214432260-737a44f0-6ff1-4618-93f3-a4175d2f70a2.png)

This error originated from a custom integration.

Logger: custom_components.wiser.config_flow
Source: custom_components/wiser/config_flow.py:60
Integration: Drayton Wiser Integration for Home Assistant (documentation, issues)
First occurred: 22:09:21 (1 occurrences)
Last logged: 22:09:21

Unknown error connecting to Wiser Hub
Traceback (most recent call last):
  File "/config/custom_components/wiser/config_flow.py", line 158, in async_step_zeroconf_confirm
    validated = await validate_input(self.hass, user_input)
  File "/config/custom_components/wiser/config_flow.py", line 60, in validate_input
    await wiserhub.read_hub_data()
  File "/usr/local/lib/python3.10/site-packages/aioWiserHeatAPI/wiserhub.py", line 188, in read_hub_data
    self._rooms = _WiserRoomCollection(
  File "/usr/local/lib/python3.10/site-packages/aioWiserHeatAPI/room.py", line 514, in __init__
    self._build()
  File "/usr/local/lib/python3.10/site-packages/aioWiserHeatAPI/room.py", line 526, in _build
    _WiserRoom(
  File "/usr/local/lib/python3.10/site-packages/aioWiserHeatAPI/room.py", line 44, in __init__
    self._extra_config = self._wiser_rest_controller._extra_config.config(
AttributeError: '_WiserRestController' object has no attribute '_extra_config'

**Comment by asantaga** [comment]
Just checking, have you entered the secret key ? Im sure the answer is yes..

Any other errors?

**Comment by msp1974** [comment]
Please use the released 3.2.2 version not the 3.2.3beta3 version for now.

**Comment by Rhysgh** [comment]
I did fry that... Let me try one more time.

**Comment by Rhysgh** [comment]
Ok the master version has worked this time,

I seem to have 2 of every entry but let me see what's what.
