### ISSUE TITLE
Setting away mode raises error but does work

### ISSUE THREAD

**Issue by broadcasttechie** [asantaga/wiserHomeAssistantPlatform#35]
Switching away mode causes the following error although it does change the mode.

If I can I'll try and see what's causing the issue.

`
Error setting Home/Away , error {"Type":"Away","SetPoint":120} 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 205, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 336, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 358, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wiser/switch.py", line 64, in turn_on
    self.handler.set_away_mode(True, self.awayTemperature)
  File "/config/custom_components/wiser/__init__.py", line 163, in set_away_mode
    self.wiserHubInstance.setHomeAwayMode(mode, away_temperature)
  File "/usr/local/lib/python3.7/site-packages/wiserHeatingAPI/wiserHub.py", line 169, in setHomeAwayMode
    raise Exception("Error setting Home/Away , error {} ".format(self.response.text))
Exception: Error setting Home/Away , error {"Type":"Away","SetPoint":120} 
Failed to call service switch/turn_off. Error setting Home/Away , error {"Type":"None","SetPoint":0}
`

**Comment by asantaga** [comment]
Found it :-)

Its in the pyheating api. If you don't pass a "away temperature" it defaults to 10.. which is 1C.. the min the wiser hub allows is 5C.. The mistake is it should have been 100
```
Line  222 : WiserHub.py : def setHomeAwayMode(self,mode,temperature=10):
``` 

Will fix this asap.

**Comment by asantaga** [comment]
Fixed in pypi and HA code (92c61fdad19e892cff69569475e4c0c527b77584) , Also released a new minor version 1.5.1  so you can just go to HACS and upgrade to 1.5.1

Seams to work for me now

(great when your working from home and decide  a bit of python is better than writing docs!)

ReOpen if it doesnt work for you

**Comment by asantaga** [comment]
im still perplexed that it didnt pass the away mode value from the HA code.. Can u check if it all works properly now?

**Comment by broadcasttechie** [comment]
Hi, thank you for the speedy fix! Yes switching the away mode now does so without generating the error (and still changes the mode on the hub) :)

**Comment by asantaga** [comment]
Awesome, closing this one
