### ISSUE TITLE
Passive Mode upsets Homekit entities

### ISSUE THREAD

**Issue by LewisSpring** [asantaga/wiserHomeAssistantPlatform#351]
Good evening,

Just noticed this in the logs:
```Logger: homeassistant.helpers.event
Source: components/homekit/type_thermostats.py:625
First occurred: February 13, 2023 at 13:17:50 (1197 occurrences)
Last logged: 21:59:07

Error while processing state change for climate.wiser_x_room
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 287, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 580, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 450, in async_update_event_state_callback
    self.async_update_state_callback(event.data.get("new_state"))
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 472, in async_update_state_callback
    self.async_update_state(new_state)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 599, in async_update_state
    self._async_update_state(new_state)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 625, in _async_update_state
    homekit_hvac_action = HC_HASS_TO_HOMEKIT_ACTION[hvac_action]
KeyError: 'Passive Mode'
```

Homekit doesn't seem to mind though:
![IMG_0785](https://user-images.githubusercontent.com/40576482/219500180-4b6e5007-d28b-4ff4-8804-f2ba3c303c10.png)
It's showing the minimum temperature and Heat Mode.

![image](https://user-images.githubusercontent.com/40576482/219500288-597ea8d8-ac03-432c-831e-305ad9b3eb58.png)

Cheers!

**Comment by msp1974** [comment]
@LewisSpring thanks for logging this.  Looking at it I think this is more a homekit issue.  HASS allows 'non standard' HVAC action values (which is what we are using to display passive mode) but Homekit errors if this is the case.  Can you log with them and I'll close this issue here.  Thanks
