### ISSUE TITLE
wiserHomeAssistantPlatform now requires python3.10

### ISSUE THREAD

**Issue by fbeziaud** [asantaga/wiserHomeAssistantPlatform#355]
# Context

From https://github.com/asantaga/wiserHomeAssistantPlatform/commit/ac9cbfc26ffa96568df87c6ecfca527d380bb500 included in v3.3.0,
the following syntax requires python3.10 (https://peps.python.org/pep-0604/).

(see the code using it here : https://github.com/asantaga/wiserHomeAssistantPlatform/blob/master/custom_components/wiser/climate.py#L228)

# Issues

With python3.9 and lower, this result in a complete incapacity to run the wiserHomeAssistantPlatform HomeAssistant plugin with the error:

```
2023-03-16 23:22:09.443 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.wiser.climate
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 744, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 761, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/wiser/climate.py", line 133, in <module>
    class WiserTempProbe(CoordinatorEntity, ClimateEntity):
  File "/home/homeassistant/.homeassistant/custom_components/wiser/climate.py", line 228, in WiserTempProbe
    def target_temperature_step(self) -> float | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
2023-03-16 23:22:09.465 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform wiser.climate: Platform not found (Exception importing custom_components.wiser.climate).
```

This is inconvenient because python3.10 is not yet included in Debian (and therefore Raspbian), which relies on python3.9 (https://packages.debian.org/stable/python/).

# Possible fixes?

Include this specific requirement in the "Minimum Requirements" readme section, even if this means more work for users on Debian-based distrib (Raspbian for example)

`or`

Remove this type of typing from the code for the time being?

**Comment by msp1974** [comment]
Its actually that the min requirements in the readme is wrong.  This integration requires HA2023.2 (which is set in the HACs config but not updated in readme).  HA2023.2 requires python3.10

Will update readme on next release.  Thanks for raising
