### ISSUE TITLE
Cannot open Settings -> Home Assistant Cloud -> Alexa: Manage Entities with this integration enabled

### ISSUE THREAD

**Issue by pdunkley** [asantaga/wiserHomeAssistantPlatform#360]
When this integration is enabled opening the above mentioned page results in the 3/4 circle continuing to show. With this integration disabled the page opens instantly.

The Home Assistand Core log file contains this error:

```
Logger: homeassistant.components.cloud.http_api
Source: components/alexa/entities.py:467
Integration: Home Assistant Cloud ([documentation](https://www.home-assistant.io/integrations/cloud), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+cloud%22))
First occurred: 13:48:33 (1 occurrences)
Last logged: 13:48:33

Unexpected error processing request for cloud/alexa/entities
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/cloud/http_api.py", line 129, in error_handler
    return await handler(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/cloud/http_api.py", line 600, in alexa_list
    entities = alexa_entities.async_get_entities(hass, alexa_config)
  File "/usr/src/homeassistant/homeassistant/components/alexa/entities.py", line 378, in async_get_entities
    if not list(alexa_entity.interfaces()):
  File "/usr/src/homeassistant/homeassistant/components/alexa/entities.py", line 467, in interfaces
    if climate.HVACMode.OFF in self.entity.attributes.get(
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by msp1974** [comment]
Don't see this happening.  Can only think if you have got a room that you have deleted that is exposed to Alexa?

**Comment by msp1974** [comment]
OK, managed to recreate and fix the issue.  v3.3.2 just released with this fix in.  Please can you test and confirm.

**Comment by pdunkley** [comment]
Looks like this has fixed it. Thanks!
