### ISSUE TITLE
Cant Control temperature

### ISSUE THREAD

**Issue by djashjones** [asantaga/wiserHomeAssistantPlatform#37]
When I adjust the temp, I get this error:

```
`2019-12-21 18:00:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140577434436560] SetRoomTemperature : value of temperature must be between 50 and 300 OR -200(off)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 205, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 336, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 360, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 519, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 380, in async_set_temperature
    ft.partial(self.set_temperature, **kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wiser/climate.py", line 175, in set_temperature
    self.handler.set_room_temperature(self.roomId, target_temperature)
  File "/config/custom_components/wiser/__init__.py", line 143, in set_room_temperature
    target_temperature)
  File "/usr/local/lib/python3.7/site-packages/wiserHeatingAPI/wiserHub.py", line 178, in setRoomTemperature
    raise Exception("SetRoomTemperature : value of temperature must be between 50 and 300 OR -200(off)")
Exception: SetRoomTemperature : value of temperature must be between 50 and 300 OR -200(off)`
```

**Comment by asantaga** [comment]
Duh,, I think I know what went wrong here..  will fix asap

**Comment by asantaga** [comment]
Ive fixed the base code but having a bit of trouble with HA.. I think its my setup.. Should be fixed tomorrow, I may release a new version of the integration just to force the pypi library upgrade.

**Comment by djashjones** [comment]
That's great news. I love your plugin.

Wiser is the only "smart" heating system in the UK I could findo that does need a cloud!

**Comment by asantaga** [comment]
> Wiser is the only "smart" heating system in the UK I could findo that does need a cloud!

You mean does NOT need a cloud eh?

**Comment by djashjones** [comment]
ha ha, thanks. more coffee needed!

**Comment by asantaga** [comment]
OK This is now fixed BUT I havent released a new HACS version until I test it properly..  I also have a PR from Mark (@msp1974 ) Id like to merge before releasing either 1.6.1 (or probably 1.7) via HACS

Can you give it a swirl and a test?

Easiest way is to clone the repo (the fixes are in the main trunk) and then replace all the files in the custom_components/wiser directory. 

The HA Integration should pull down the latest wiser-api from pypi..

Let me know how this works

**Comment by djashjones** [comment]
Great Job, all back to normal. well apart from the trv issue

**Comment by asantaga** [comment]
Cool closing ticket
