### ISSUE TITLE
Lights AND Shutters

### ISSUE THREAD

**Issue by LGO44** [asantaga/wiserHomeAssistantPlatform#375]
Running :
Home Assistant 2023.8.0
Supervisor 2023.07.1
Operating System 10.4
Interface utilisateur : 20230802.0 - latest

Wiser API: 1.3.4
Wiser : 3.3.7

Firmware hub : 3.14

The lights and shutters don't work anymore. The devices wiser_*_light and wiser_shutter_*control are not initialise correctly.

I search a cause for these issues and I have to modify the light.py and cover.py as following 
I let the expression as comment

 **       #"serial_number": self._data.wiserhub.devices.get_by_id(
            #    self._device_id
            #).serial_number,
            #"product_type": self._device.product_type,
            #"product_identifier": self._device.product_identifier,
            #"via_device": (DOMAIN, self._data.wiserhub.system.name),**

**light.py**

class WiserLight(CoordinatorEntity, LightEntity, WiserScheduleEntity):
    """WiserLight ClientEntity Object."""

    def __init__(self, coordinator, light_id):
        """Initialize the sensor."""
        super().__init__(coordinator)
        self._data = coordinator
        self._device_id = light_id
        self._device = self._data.wiserhub.devices.lights.get_by_id(self._device_id)
        self._schedule = self._device.schedule
        _LOGGER.debug(f"{self._data.wiserhub.system.name} {self.name} initialise")

    async def async_force_update(self, delay: int = 0):
        _LOGGER.debug(f"Hub update initiated by {self.name}")
        if delay:
            await asyncio.sleep(delay)
        await self._data.async_refresh()

    @callback
    def _handle_coordinator_update(self) -> None:
        _LOGGER.debug(f"{self.name} updating")
        self._device = self._data.wiserhub.devices.lights.get_by_id(self._device_id)
        self._schedule = self._device.schedule
        self.async_write_ha_state()

    @property
    def supported_color_modes(self):
        return {ColorMode.ONOFF}

    @property
    def is_on(self):
        """Return the boolean response if the node is on."""
        return self._device.is_on

    @property
    def name(self):
        """Return the name of the Device."""
        return f"{get_device_name(self._data, self._device.id)} Light"

    @property
    def icon(self):
        """Return icon."""
        if self._device.mode == "Auto":
            return "mdi:lightbulb-auto" if self.is_on else "mdi:lightbulb-auto-outline"
        else:
            return "mdi:lightbulb" if self.is_on else "mdi:lightbulb-outline"

    @property
    def unique_id(self):
        return get_unique_id(self._data, "device", "light", self.name)

    @property
    def device_info(self):
        """Return device specific attributes."""
        return {
            "name": get_device_name(self._data, self._device_id),
            "identifiers": {(DOMAIN, get_identifier(self._data, self._device_id))},
            "manufacturer": MANUFACTURER,
            "model": self._data.wiserhub.devices.get_by_id(self._device_id).model,
            "sw_version": self._device.firmware_version,
            **#"serial_number": self._data.wiserhub.devices.get_by_id(
            #    self._device_id
            #).serial_number,
            #"product_type": self._device.product_type,
            #"product_identifier": self._device.product_identifier,
            #"via_device": (DOMAIN, self._data.wiserhub.system.name),**
        }

**In cover.py**

class WiserShutter(CoordinatorEntity, CoverEntity, WiserScheduleEntity):
    """Wisershutter ClientEntity Object."""

    def __init__(self, coordinator, shutter_id):
        """Initialize the sensor."""
        super().__init__(coordinator)
        self._data = coordinator
        self._device_id = shutter_id
        self._device = self._data.wiserhub.devices.shutters.get_by_id(self._device_id)
        self._schedule = self._device.schedule
        _LOGGER.debug(f"{self._data.wiserhub.system.name} {self.name} initialise")

    async def async_force_update(self, delay: int = 0):
        _LOGGER.debug(f"Hub update initiated by {self.name}")
        if delay:
            asyncio.sleep(delay)
        await self._data.async_refresh()

    @callback
    def _handle_coordinator_update(self) -> None:
        _LOGGER.debug(f"{self.name} updating")
        self._device = self._data.wiserhub.devices.shutters.get_by_id(self._device_id)
        self._schedule = self._device.schedule
        self.async_write_ha_state()

    @property
    def supported_features(self):
        """Flag supported features."""
        return SUPPORT_FLAGS

    # TODO: What is this for?
    @property
    def scheduled_position(self):
        """Return scheduled position from data."""
        return self._device.scheduled_lift

    @property
    def device_info(self):
        """Return device specific attributes."""
        return {
            "name": get_device_name(self._data, self._device_id),
            "identifiers": {(DOMAIN, get_identifier(self._data, self._device_id))},
            "manufacturer": MANUFACTURER,
            "model": self._data.wiserhub.devices.get_by_id(self._device_id).model,
            #"serial_number": self._data.wiserhub.devices.get_by_id(
            #    self._device_id
            #).serial_number,
            #"product_type": self._device.product_type,
            #"product_identifier": self._device.product_identifier,
            #"via_device": (DOMAIN, self._data.wiserhub.system.name),
        }

**logs representing the issue**

2023-08-03 18:49:54.702 ERROR (MainThread) [homeassistant.components.light] Error adding entities for domain light with platform wiser
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
device = dev_reg.async_get(self.hass).async_get_or_create(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'serial_number'
2023-08-03 18:49:54.732 ERROR (MainThread) [homeassistant.components.light] Error while setting up wiser platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 370, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
device = dev_reg.async_get(self.hass).async_get_or_create(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'serial_number'

**Comment by msp1974** [comment]
Fixed in 3.3.8
