### ISSUE TITLE
Fatal error on upgrade from v3.3.11 -> v3.4.0

### ISSUE THREAD

**Issue by davethebug** [asantaga/wiserHomeAssistantPlatform#409]
On upgrading via HACS to 3.4 the following logs prevented the wiser integration from starting. Tested on current HA OS/version and previous snapshot.  (I only installed it 2 days ago!)

All help much appreciated. 

Logs: 
Unexpected error fetching wiser (wiser-WiserHeat0575C3) data: Illegal header value b' hG--redacted-wiser-key--e+r2--redacted--a/fqMw9/Mw/u2--redacted--q'
6 December 2023, 22:28:15 – (ERROR) Drayton Wiser Integration for Home Assistant (custom integration) - message first occurred at 6 December 2023, 22:27:54 and shows up 3 times
Illegal header value b' hG--redacted-wiser-key--e+r2--redacted--a/fqMw9/Mw/u2--redacted--q'
6 December 2023, 22:28:15 – (ERROR) Drayton Wiser Integration for Home Assistant (custom integration) - message first occurred at 6 December 2023, 22:27:54 and shows up 3 times

detailed log

2023-12-06 22:27:54.486 ERROR (MainThread) [custom_components.wiser.coordinator] Illegal header value b' hG--redacted-wiser-key--e+r2--redacted--a/fqMw9/Mw/u2--redacted--q'
2023-12-06 22:27:54.486 ERROR (MainThread) [custom_components.wiser.coordinator] Unexpected error fetching wiser (wiser-WiserHeat0575C3) data: Illegal header value b' hG--redacted-wiser-key--e+r2--redacted--a/fqMw9/Mw/u2--redacted--q'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 142, in _send_request_headers
    event = h11.Request(
            ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/h11/_events.py", line 96, in __init__
    self, "headers", normalize_and_validate(headers, _parsed=_parsed)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/h11/_headers.py", line 164, in normalize_and_validate
    validate(_field_value_re, value, "Illegal header value {!r}", value)
  File "/usr/local/lib/python3.11/site-packages/h11/_util.py", line 91, in validate
    raise LocalProtocolError(msg)
h11._util.LocalProtocolError: Illegal header value b' hG--redacted-wiser-key--e+r2--redacted--a/fqMw9/Mw/u2--redacted--q'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Etc..

**Comment by msp1974** [comment]
Seems it doesn't like your secret key value.  Not that it is wrong but it doesn't like it.

Few questions.

1. Presume this was working on 3.3.11?
2. What version  of HA are you on?
3. What hub do you have?

**Comment by davethebug** [comment]
1. Worked well on 3.3.11 and when I fell back to that version. 
2. Happens on 2023.11 and 2023.12  using HAOS 11.2 
3. Hub R WT724R1S0902 running 3.12.1

I left the special charters in the redaction blah+blah/blah/blah/blah  - Probably useless info, but I setup the integration and copied the key in from an iPad.

**Comment by SteveJack34** [comment]
I have the same issue. There appears to be a space at the end of the header value.
SteveJ

**Comment by msp1974** [comment]
This shounow be fixed (without editing the config files) in v3.4.1
