### ISSUE TITLE
V3.4.7 : Warning: color mode [stop working in 2025.3] 

### ISSUE THREAD

**Issue by senna1992** [asantaga/wiserHomeAssistantPlatform#479]
The latest update provides me with this error: 

`light.licht_8 (<class 'custom_components.wiser.light.WiserLight'>) set to unsupported color mode {<ColorMode.ONOFF: 'onoff'>}, expected one of {<ColorMode.ONOFF: 'onoff'>}, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/asantaga/wiserHomeAssistantPlatform/issues`

`Logger: homeassistant.helpers.event
Quelle: helpers/event.py:327
Erstmals aufgetreten: 8. Mai 2024 um 23:09:08 (1 Vorkommnisse)
Zuletzt protokolliert: 8. Mai 2024 um 23:09:08

Error while dispatching event for light.licht_8 to <Job track state_changed event ['light.licht_1', 'light.licht_2', 'light.licht_3', 'light.licht_4', 'light.licht_5_1', 'light.licht_7_1', 'light.licht_7_2', 'light.licht_9_2', 'light.licht_8', 'light.licht_9_1'] HassJobType.Callback <function GroupEntity.async_added_to_hass.<locals>.async_state_changed_listener at 0x7f8ec34cc0>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 327, in _async_dispatch_entity_id_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 947, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/group/entity.py", line 90, in async_state_changed_listener
    self.async_defer_or_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/components/group/entity.py", line 111, in async_defer_or_update_ha_state
    self.async_update_group_state()
  File "/usr/src/homeassistant/homeassistant/components/group/light.py", line 284, in async_update_group_state
    color_mode_count = Counter(itertools.chain(all_color_modes))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/collections/__init__.py", line 607, in __init__
    self.update(iterable, **kwds)
  File "/usr/local/lib/python3.12/collections/__init__.py", line 698, in update
    _count_elements(self, iterable)
TypeError: unhashable type: 'set'`

**Comment by senna1992** [comment]
[config_entry-wiser-9b53e456ad3705a3e39faa20b40d008b.json](https://github.com/asantaga/wiserHomeAssistantPlatform/files/15267397/config_entry-wiser-9b53e456ad3705a3e39faa20b40d008b.json)


Debug log, if helpful. 
Device is reproted as "1GANG/SWITCH/1" by "Schneider Electric" Firmware: 2.10.1

**Comment by msp1974** [comment]
This should now be resolved in 3.4.8.  Sorry for the long delay,
