### ISSUE TITLE
Detected blocking call to listdir

### ISSUE THREAD

**Issue by msp1974** [asantaga/wiserHomeAssistantPlatform#493]
Detected blocking call to listdir with args ('/config/custom_components/wiser/frontend',) inside the event loop by custom integration 'wiser' at custom_components/wiser/frontend/__init__.py, line 123: filename for filename in os.listdir(path) if filename.endswith(".gz") (offender: /config/custom_components/wiser/frontend/__init__.py, line 123: filename for filename in os.listdir(path) if filename.endswith(".gz")), please create a bug report at https://github.com/asantaga/wiserHomeAssistantPlatform/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/wiser/__init__.py", line 65, in async_setup_entry await cards.async_register() File "/config/custom_components/wiser/frontend/__init__.py", line 19, in async_register await self.async_wait_for_lovelace_resources() File "/config/custom_components/wiser/frontend/__init__.py", line 40, in async_wait_for_lovelace_resources await check_lovelace_resources_loaded(0) File "/config/custom_components/wiser/frontend/__init__.py", line 33, in check_lovelace_resources_loaded await self.async_register_wiser_cards() File "/config/custom_components/wiser/frontend/__init__.py", line 76, in async_register_wiser_cards await self.async_remove_gzip_files() File "/config/custom_components/wiser/frontend/__init__.py", line 123, in async_remove_gzip_files filename for filename in os.listdir(path) if filename.endswith(".gz")

**Comment by msp1974** [comment]
Resolved in 3.4.9
