### ISSUE TITLE
Regression in sensors for UK heat hubs in v3.4.9

### ISSUE THREAD

**Issue by janstenpickle** [asantaga/wiserHomeAssistantPlatform#513]
I have an older heat hub model `WT714R1S0902`. It seems that #499 has removed the OpenTherm sensors from that device, despite it having an OpenTherm interface.

Rolling back to v3.4.8 resolves the issue

**Comment by MelHarbour** [comment]
Yep, confirmed that it broke my system as well. I haven't got OpenTherm though - it just broke the ability to pull any information off the hub apparently.

Again, rolling back to v3.4.8 fixed it for me as well.

**Comment by enthalpie91** [comment]
I confirm some sensor are'nt available

**Comment by msp1974** [comment]
Can you all please provide diagnostics files and proper detail of what exactly is missing error logs, so I can understand the issue. Thanks

**Comment by andyblac** [comment]
same here it's worse even my heating control is now not working.

<img width="1057" alt="Screenshot 2024-11-01 at 20 53 54" src="https://github.com/user-attachments/assets/83dfaf6e-dee8-4a7a-bc4b-910b9e34c5cc">
[config_entry-wiser-8b929c1b9da8ccf0a3de2fceb5dcc65f-2.json](https://github.com/user-attachments/files/17604067/config_entry-wiser-8b929c1b9da8ccf0a3de2fceb5dcc65f-2.json)

**Comment by sammyh2506** [comment]
Same issues with numerous wiser sensors not available...

Noticed this in the logs:

Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:724
integration: Climate (documentation, issues)
First occurred: 22:19:03 (1 occurrences)
Last logged: 22:19:03

wiser: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 724, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 571, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/wiser/sensor.py", line 361, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1071, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wiser/sensor.py", line 509, in extra_state_attributes
    device_id = self._data.wiserhub.devices.get_by_id(self._device_id).id
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by mrpp** [comment]
Crashed mine too, lost most sensors, reverted back to 3.4.8

**Comment by msp1974** [comment]
All,  sorry about that.  It seems I had picked up the issue but not pushed it before release.  v3.4.10 just released and should now be resolved.

Thanks @sammyh2506 for the log and @andyblac for the diagnostic.

**Comment by janstenpickle** [comment]
Thankyou @msp1974, this is resolved in #515 for me!

<img width="337" alt="image" src="https://github.com/user-attachments/assets/03082d70-ac42-4e9d-8d41-fe2a33a6a0cd">

**Comment by andyblac** [comment]
> All, sorry about that. It seems I had picked up the issue but not pushed it before release. v3.4.10 just released and should now be resolved.
> 
> Thanks @sammyh2506 for the log and @andyblac for the diagnostic.

all good now, thanks.
