### ISSUE TITLE
Unable to start up platform

### ISSUE THREAD

**Issue by lewisbeard** [asantaga/wiserHomeAssistantPlatform#53]
I get this error in log when I restart home assistant after configuring WiserHomeAssistant with HACS. I'm unable to add WiserHomeAssistant as an integration (apologies if something simple I'm new to HA). Thanks 

Error while setting up platform wiser
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 158, in _async_setup_platform
await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
return fut.result()
File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/wiser/climate.py", line 56, in setup_platform
handler.update()
File "/config/custom_components/wiser/init.py", line 106, in update
self.wiserHubInstance = wiserHub.wiserHub(self.ip, self.secret)
File "/usr/local/lib/python3.7/site-packages/wiserHeatingAPI/wiserHub.py", line 47, in init
self.refreshData() # Issue first refresh in init
File "/usr/local/lib/python3.7/site-packages/wiserHeatingAPI/wiserHub.py", line 87, in refreshData
self.hubIP), headers=self.headers, timeout=TIMEOUT).json()
File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/local/lib/python3.7/site-packages/simplejson/init.py", line 525, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
obj, end = self.raw_decode(s)
File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by msp1974** [comment]
@lewisbeard can you share your wiser config from configuration.yaml

**Comment by asantaga** [comment]
Closing this ticket for now, @lewisbeard  , if the problem persists let us know
