### ISSUE TITLE
Climate Preset modes work but give an erroneous error message

### ISSUE THREAD

**Issue by pdoubleyou** [asantaga/wiserHomeAssistantPlatform#550]
Using wiser integration to control central heating room thermostat and radiator valves. When I select any boost mode, the indicator shows the device active, it functions correctly, but a warning message shows the following
"Preset mode is not valid. Valid preset modes are: Advance Schedule, Cancel Overrides, Boost 30m, Boost 1h, Boost 2h, Boost 3h."
Cannot say for sure if it is a result of a recent update because I did not have the preset modes active

**Comment by freshfieldx** [comment]
I'm also seeing errors with presets:

Log details (ERROR)
This error originated from a custom integration.
Logger: homeassistant
Source: custom_components/wiser/helpers.py:36
integration: Drayton Wiser Integration for Home Assistant (documentation, issues)
First occurred: 10:36:33 (332 occurrences)
Last logged: 13:33:38

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 267, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/wiser/sensor.py", line 388, in _handle_coordinator_update
    super()._handle_coordinator_update()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/wiser/sensor.py", line 267, in _handle_coordinator_update
    _LOGGER.debug(f"{self.name} device update requested")
                     ^^^^^^^^^
  File "/config/custom_components/wiser/sensor.py", line 410, in name
    return f"{get_device_name(self._data, self._device_id)} Signal"
              ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wiser/helpers.py", line 36, in get_device_name
    if device.product_type == "iTRV":
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'product_type'

**Comment by msp1974** [comment]
> I'm also seeing errors with presets:
> 
> Log details (ERROR) This error originated from a custom integration. Logger: homeassistant Source: custom_components/wiser/helpers.py:36 integration: Drayton Wiser Integration for Home Assistant (documentation, issues) First occurred: 10:36:33 (332 occurrences) Last logged: 13:33:38
> 
> Error doing job: Task exception was never retrieved (None) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 267, in _handle_refresh_interval await self._async_refresh(log_failures=True, scheduled=True) File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh self.async_update_listeners() ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^ File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners update_callback() ~~~~~~~~~~~~~~~^^ File "/config/custom_components/wiser/sensor.py", line 388, in _handle_coordinator_update super()._handle_coordinator_update() ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/wiser/sensor.py", line 267, in _handle_coordinator_update _LOGGER.debug(f"{self.name} device update requested") ^^^^^^^^^ File "/config/custom_components/wiser/sensor.py", line 410, in name return f"{get_device_name(self._data, self._device_id)} Signal" ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/wiser/helpers.py", line 36, in get_device_name if device.product_type == "iTRV": ^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'product_type'

This is not the same issue. Please can you log a new issue and provide a diagnostic file.

**Comment by msp1974** [comment]
@pdoubleyou, I cannot recreate this (this was an issue in a previous version).  Can you confirm you HA and Wiser integration versions.  Thx

**Comment by pdoubleyou** [comment]
hi Mark

Home Assistant

   - Core 2024.12.5
   - Supervisor 2024.12.3
   - Operating System 14.1
   - Frontend 20241127.8

Wiser  3.4.15

If it helps Wiser diagnostics is attached, also screenshot of the message
when i've clicked on a boost button. As stated, the boost does work, its
just the erroneous message that is appearing

Regards
Phil

**Comment by fascinatedcow** [comment]
Same here with ~HA `2025.1.0` (container version) and Wiser `3.4.15` (via HACS). I have only a hub and thermostat, no TRVs.

**Comment by lagore** [comment]
I see the same error when doing an 'Advance Schedule', it works correctly but gives

ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139912436030992] Preset mode  is not valid. Valid preset modes are: Advance Schedule, Cancel Overrides, Boost 30m, Boost 1h, Boost 2h, Boost 3h

Wiser 3.4.15
HA core 2024.12.3
Thanks
Edward

**Comment by msp1974** [comment]
I have been struggling to recreate this issue but have now been able to.  Am I correct in assuming you are all using the drop down selector for presets and not the icons?  Seems in icon mode (which I use) the error does not happen, but in dropdown mode it does.

I am going to log this with HA frontend as it should be at least consistent and I think setting the preset to None (which is what is causing the error), shoudl not error.

**Comment by pdoubleyou** [comment]
I use drop-down mode, and get the error. I didn't know about an icon mode
tho.
Pw

**Comment by lagore** [comment]
Hi Mark,
I just changed one of my controls to icon mode and it works without throwing the error, well done with finding the cause.
Edward

**Comment by msp1974** [comment]
Closing this as a HA quirk with workaround.
