### ISSUE TITLE
error setting up wiser switches

### ISSUE THREAD

**Issue by phixion** [asantaga/wiserHomeAssistantPlatform#73]
I was wondering why my away-mode (wiser heating) switch was gone. It seems latest version cannot setup its switches:

```
Error while setting up wiser platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/wiser/switch.py", line 45, in async_setup_platform
    WiserSmartPlug(hass, data, plug.get("id"), plug.get("Name")) for plug in data.wiserhub.getSmartPlugs()
TypeError: 'NoneType' object is not iterable
```

Maybe its because I dont have any smartplugs from wiser?

**Comment by scooper1** [comment]
Lastest version ment to fix smartplug issue

Sent from Yahoo Mail on Android 
 
  On Thu, 27 Feb 2020 at 16:23, Martin Spitz<notifications@github.com> wrote:   
I was wondering why my away-mode (wiser heating) switch was gone. It seems latest version cannot setup its switches:
Error while setting up wiser platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/wiser/switch.py", line 45, in async_setup_platform
    WiserSmartPlug(hass, data, plug.get("id"), plug.get("Name")) for plug in data.wiserhub.getSmartPlugs()
TypeError: 'NoneType' object is not iterable

Maybe its because I dont have any smartplugs from wiser?

**Comment by phixion** [comment]
reinstalled via HACS and all switches are back now. SOrry for wasting your time

**Comment by asantaga** [comment]
no thats ok, it appears to be a common problem, the upgrade in HACS isnt doing the job properly..
